# Generated by Django 5.1.2 on 2024-12-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("head", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="head",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_id",
                    models.CharField(
                        blank=True, default="395ba782", max_length=8, unique=True
                    ),
                ),
                (
                    "admin_name_first",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "admin_name_last",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "admin_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "admin_password",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "admin_phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "admin_verify_code",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("is_staff", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="ind_adminDT",
        ),
    ]
