# Generated by Django 5.1.2 on 2024-12-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("head", "0008_alter_head_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="head",
            name="admin_id",
            field=models.CharField(
                blank=True, default="ae61f8b4", max_length=8, unique=True
            ),
        ),
    ]
