# Generated by Django 5.1.2 on 2024-12-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("head", "0013_alter_head_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="head",
            name="admin_id",
            field=models.CharField(
                blank=True, default="c3be97c6", max_length=8, unique=True
            ),
        ),
    ]
