# Generated by Django 5.1.2 on 2024-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("head", "0016_lead_active_lead_assigned_to_alter_head_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="head",
            name="admin_id",
            field=models.CharField(
                blank=True, default="6c2e2008", max_length=8, unique=True
            ),
        ),
    ]
