# Generated by Django 5.1.2 on 2024-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("head", "0023_alter_head_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="head",
            name="admin_id",
            field=models.CharField(
                blank=True, default="6699ff84", max_length=8, unique=True
            ),
        ),
    ]
