# Generated by Django 5.1.1 on 2024-12-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0014_alter_super_admin_super_admin_id_delete_employeedt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.CharField(blank=True, default='a72f4a74', max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('Employee_admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='crm.super_admin')),
            ],
        ),
    ]
