# Generated by Django 5.1.1 on 2024-12-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('crm', '0015_alter_super_admin_super_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedt',
            name='Employee_admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='crm.super_admin'),
        ),
        migrations.AlterField(
            model_name='employeedt',
            name='Employee_id',
            field=models.CharField(blank=True, default='8100957c', max_length=8, unique=True),
        ),
    ]
