# Generated by Django 5.1.2 on 2024-12-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee", "0004_alter_employeedt_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedt",
            name="Employee_id",
            field=models.CharField(
                blank=True, default="b15ce99d", max_length=8, unique=True
            ),
        ),
    ]
