# Generated by Django 5.1.2 on 2024-12-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee", "0020_alter_employeedt_employee_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeedt",
            name="Employee_admin_id",
        ),
        migrations.AlterField(
            model_name="employeedt",
            name="Employee_id",
            field=models.CharField(
                blank=True, default="c1955ed1", max_length=8, unique=True
            ),
        ),
    ]
