# Generated by Django 5.1.2 on 2024-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee", "0021_remove_employeedt_employee_admin_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedt",
            name="Employee_id",
            field=models.CharField(
                blank=True, default="5e99e9ed", max_length=8, unique=True
            ),
        ),
    ]
