# Generated by Django 5.0.4 on 2024-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_super_admin_alter_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_admin',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='5618212c', max_length=8, unique=True),
        ),
    ]
