# Generated by Django 5.0.4 on 2024-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_super_admin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='09ed9bf5', max_length=8, unique=True),
        ),
    ]
