# Generated by Django 5.0.4 on 2024-08-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_super_admin_super_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='6b76c09b', max_length=8, unique=True),
        ),
    ]
