# Generated by Django 5.1.1 on 2024-11-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_admin',
            name='facebook_app_id',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='super_admin',
            name='facebook_app_secret',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('organic_search', 'Organic Search'), ('google_ad', 'Google Ad'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('Self', 'Self')], default='facebook', help_text='Where Lead found us', max_length=50),
        ),
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='bab01faf', max_length=8, unique=True),
        ),
    ]
