# Generated by Django 5.1.1 on 2024-11-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_customer_admin_id_super_admin_sub_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='admin_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='761de2ae', max_length=8, unique=True),
        ),
    ]
