# Generated by Django 5.1.1 on 2024-11-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_super_admin_super_admin_id_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Lead'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('FOLLOWUP', 'Follow-Up')], default='NEW', help_text="Lead's status for tracking and communication", max_length=50),
        ),
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='10ae7bd3', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='crm.super_admin'),
        ),
    ]
