# Generated by Django 5.1.1 on 2024-12-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customer_status_alter_super_admin_super_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='2e8bc6a6', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='EmployeeDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.CharField(blank=True, default='a10657a2', max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('Employee_admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='crm.super_admin')),
            ],
        ),
    ]
