# Generated by Django 5.1.1 on 2024-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_super_admin_super_admin_id_delete_employeedt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='749b085b', max_length=8, unique=True),
        ),
    ]
