# Generated by Django 5.0.4 on 2024-12-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_super_admin_super_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_admin',
            name='super_admin_id',
            field=models.CharField(blank=True, default='cb0b5360', max_length=8, unique=True),
        ),
    ]
