# Generated by Django 5.1.2 on 2024-12-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0018_alter_super_admin_super_admin_id_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="4e797aa4", max_length=8, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
