# Generated by Django 5.1.2 on 2024-12-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0019_alter_super_admin_super_admin_id_delete_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="city",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="page",
        ),
        migrations.AddField(
            model_name="form",
            name="status",
            field=models.CharField(
                blank=True, default="INACTIVE", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="crm.form",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="page",
            name="access_token",
            field=models.TextField(default="default_token"),
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="e9757432", max_length=8, unique=True
            ),
        ),
    ]
