# Generated by Django 5.1.2 on 2024-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0020_remove_lead_assigned_to_remove_lead_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="a8149d6e", max_length=8, unique=True
            ),
        ),
    ]
