# Generated by Django 5.1.2 on 2024-12-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0023_alter_super_admin_super_admin_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="super_admin",
            name="facebook_app_id",
        ),
        migrations.RemoveField(
            model_name="super_admin",
            name="facebook_app_secret",
        ),
        migrations.AddField(
            model_name="super_admin",
            name="allowed_pages",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="c370cb98", max_length=8, unique=True
            ),
        ),
    ]
