# Generated by Django 5.1.2 on 2024-12-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0025_remove_super_admin_allowed_pages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="allowed_pages",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_subadmins", to="crm.page"
            ),
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="8f914d97", max_length=8, unique=True
            ),
        ),
    ]
