# Generated by Django 5.1.2 on 2024-12-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0026_alter_super_admin_allowed_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True, related_name="pages_visible", to="crm.super_admin"
            ),
        ),
        migrations.AddField(
            model_name="super_admin",
            name="role",
            field=models.CharField(
                choices=[("subadmin", "Sub-Admin"), ("admin", "Admin")],
                default="subadmin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="allowed_pages",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_superadmins", to="crm.page"
            ),
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="2926d51c", max_length=8, unique=True
            ),
        ),
    ]
