# Generated by Django 5.1.2 on 2024-12-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0028_remove_super_admin_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="2c833135", max_length=8, unique=True
            ),
        ),
    ]
