# Generated by Django 5.1.2 on 2024-12-13 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0032_alter_super_admin_super_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="a1ac5800", max_length=8, unique=True
            ),
        ),
    ]
