# Generated by Django 5.1.2 on 2024-12-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0033_alter_lead_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="8d9167c0", max_length=8, unique=True
            ),
        ),
    ]
