# Generated by Django 5.1.2 on 2024-12-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0037_lead_active_lead_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="967a585e", max_length=8, unique=True
            ),
        ),
    ]
