# Generated by Django 5.1.2 on 2024-12-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0038_alter_super_admin_super_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="c5fdd5a6", max_length=8, unique=True
            ),
        ),
    ]
