# Generated by Django 5.1.2 on 2024-12-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0044_alter_super_admin_super_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="lead_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="bdcf04bf", max_length=8, unique=True
            ),
        ),
    ]
