# Generated by Django 5.1.2 on 2024-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0047_alter_super_admin_super_admin_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="85baa569", max_length=8, unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="lead",
            table="crm_lead",
        ),
    ]
