# Generated by Django 5.1.2 on 2024-12-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0048_alter_lead_options_alter_super_admin_super_admin_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="super_admin",
            name="super_admin_id",
            field=models.CharField(
                blank=True, default="a449c639", max_length=8, unique=True
            ),
        ),
    ]
